name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: carlosportella16
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/ocean.gif?palette=github-dark

      - name: Deploy Snake
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
